stages:
  - initial
  - scan
  - build
  - deploy
  - test

include:
  - project: 'iiidevops-templates/ci-template'
    ref: 'v2.1.1'
    file: 'ci/template.gitlab-ci.yml'
  - project: 'iiidevops-templates/ci-template'
    ref: 'v2.1.1'
    file: 'job/DeployDatabase.gitlab-ci.yml'

Deploy--Database:
  variables:
    iiidevops: deployed-environments
    CHART_DB_GUI: "true"
    CHART_DB_NAME: "todo_db"
    CHART_DB_USERNAME: "iiidevops"
    CHART_DB_PASSWORD: "DevOps_123"
    CHART_DB_TAG: "13"
    CHART_DB_TYPE: "postgresql"
    CHART_NFS_ENABLED: "false"
    CHART_NFS_SERVER_IP: "10.20.0.100"
    CHART_VERSION: "0.4.1"
  only:
    - master

Deploy--Wait DB deployment:
  variables:
    iiidevops: deployed-environments
    max_wait: 128
  only:
    - master

