include:
- project: iiidevops-templates/ci-template
  ref: v2.12.3
  file: ci/template.gitlab-ci.yml
- project: iiidevops-templates/ci-template
  ref: v2.12.3
  file: job/DeployDatabase.gitlab-ci.yml
- local: iiidevops/jobs/*.yml

stages:
- initial
- scan
- build
- deploy
- test
- userjobs

Deploy--Database:
  variables:
    iiidevops: deploy-db
    CHART_DB_GUI: 'true'
    CHART_DB_NAME: todo_db
    CHART_DB_USERNAME: iiidevops
    CHART_DB_PASSWORD: DevOps_123
    CHART_DB_TAG: '13'
    CHART_DB_TYPE: postgresql
    CHART_VOLUME_ENABLED: 'false'
    
Deploy--Wait DB deployment:
  variables:
    iiidevops: deploy-db
    max_wait: 128
    
